name: Darwin-Cross

on:

  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: macOS build cmd
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build ./cmd/...

    - name: macOS build tests
      env:
        GOOS: darwin
        GOARCH: amd64
      run: for d in $(go list -f '{{if .TestGoFiles}}{{.Dir}}{{end}}' ./... ); do (echo $d; cd $d && go test -c ); done

    - name: macOS install cmd
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go install tailscale.com/cmd/tailscale{,d}@main

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: $HOME/go/bin/tailscaled